### ISSUE TITLE
Get build Error when adding 'darryncampbell-cordova-plugin-intent'

### ISSUE THREAD

**Issue by pilz97** [darryncampbell/darryncampbell-cordova-plugin-intent#59]
Hello,

when I add the plugin I get the folling error:
`A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:27.1.0.
     Searched in the following locations: ....
`
Angular-Cli: 6.1.4
Cordova: 8.0.0

When I remove the plugin everything works fine.

**Comment by darryncampbell** [comment]
Strange.  Are you able to build https://github.com/darryncampbell/plugin-intent-api-exerciser?  It could be some interaction with some other Plugin.  Also, perhaps try v1.1.0 of this plugin, I pushed a change yesterday to create 1.1.1 but I'm always suspicious of issues raised immediately after an update.

**Comment by pilz97** [comment]
I can build  https://github.com/darryncampbell/plugin-intent-api-exerciser!
Same issue with v1.1.0 :(

**Comment by darryncampbell** [comment]
Interesting... maybe it is some conflict... what other plugins are you using in your app?

**Comment by pilz97** [comment]
Hm doesn't fix my error..

I Changed the android version to v6.3.0 instead of v6.2.3 (because there was a warning in the build..)
Now i get a other error:

`Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCom
pat$AccessibilityServiceInfoVersionImpl;
`

**Comment by darryncampbell** [comment]
Ah, that's one difference with my set-up, is there any reason you can't upgrade to android 7.x? (I have 7.0)

**Comment by pilz97** [comment]
Ok but this error happens due to a other plugin!

Yes because the app should be available for devices with Android >=6, the most devices which are using the apk have android 6!

One last question:
this is my Intent-Call 
`    window.plugins.intentShim.startActivity(
      {
        action: "com.six.payment.services.pay.PURCHASE",
        extras: {
          Exponent: 2,
          TipAllowed: false,
          Amount: 10,
          Currency: 'EUR',
          AdditionalMerchantData: '',
          TerminalID: '23509094'        }
      },
      function(intent) {this.onSuccess(intent); alert('result code:' + intent.extras.requestCode)},
      function() {alert('Failed to open URL via Android Intent')}
    );`

Is there anything wrong? I don't get the alert..

Thank you so much for your help!

**Comment by snazaca02** [comment]
Hi, I'm running into the same issue and I have been trying to install the correct support library. However after installing the android support repository through the Android SDK GUI it doesn't include the support library for 27.1.0.
 
After looking on their site they said they were discontinuing the GUI; So I went to the maven they direct you to install it manually. It either has bad 404 requests or not all of the files needed for the android support v4:27.1.0

Do you happen to know where I can find it and go about resolving this issue? or if there is some other way? I'm not seeing any other way to use intents in my environment outside of your plugin. Any help would be greatly appreciated. I believe if I get the correct library I should be able to build this just fine.

**Comment by darryncampbell** [comment]
If it is the same issue, can you ensure you are building with Cordova Android 7.x and then remove all other plugins - it should then build... then start adding the plugins back in one by one to identify where there is incompatibility.

**Comment by darryncampbell** [comment]
Closing - presuming resolved
